"""add documents and chunks

Knowledge-base documents and the embedded chunks retrieval searches.

Drafted with --autogenerate and then corrected. Two defects in the draft, both
worth knowing about because they will recur:

* Autogenerate proposed ``op.drop_constraint('ck_tickets_status_valid')``. That
  constraint is generated by ``Enum(native_enum=False, create_constraint=True)``
  rather than declared in ``__table_args__``, and the comparison does not match
  it against the model -- so every future autogenerate will offer to delete the
  ticket status validation. It is removed here, and a test asserts no migration
  ever drops it.
* The draft referenced ``pgvector.sqlalchemy.vector.VECTOR`` without importing
  ``pgvector``, which would have failed with NameError on the first run.

``CREATE EXTENSION vector`` runs here rather than being a manual setup step, so
a fresh database reaches a working state from migrations alone. The downgrade
deliberately does not drop the extension: other objects in the database may
depend on it, and removing a shared extension to undo one revision is not a
trade this migration is entitled to make.

Revision ID: 5f02b1107b3f
Revises: 6dd90e1db408
Create Date: 2026-09-01
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

revision: str = "5f02b1107b3f"
down_revision: str | Sequence[str] | None = "6dd90e1db408"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIMENSIONS = 384


def upgrade() -> None:
    """Create the documents and document_chunks tables."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("length(btrim(content)) > 0", name=op.f("ck_documents_content_not_blank")),
        sa.CheckConstraint("length(btrim(title)) > 0", name=op.f("ck_documents_title_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_index("ix_documents_created_at", "documents", ["created_at"], unique=False)

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.Vector(EMBEDDING_DIMENSIONS),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("length(btrim(content)) > 0", name=op.f("ck_document_chunks_content_not_blank")),
        sa.CheckConstraint("ordinal >= 0", name=op.f("ck_document_chunks_ordinal_non_negative")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_chunks_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_chunks")),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_document_chunks_document_id_ordinal"),
    )
    op.create_index(
        "ix_document_chunks_document_id", "document_chunks", ["document_id"], unique=False
    )
    # Cosine operator class: the embedding model returns L2-normalised vectors,
    # so ranking by the default L2 class would order by a distance they were
    # not built for.
    op.create_index(
        "ix_document_chunks_embedding",
        "document_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )


def downgrade() -> None:
    """Drop both tables, children first. The extension is left in place."""
    op.drop_index(
        "ix_document_chunks_embedding",
        table_name="document_chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index("ix_document_chunks_document_id", table_name="document_chunks")
    op.drop_table("document_chunks")
    op.drop_index("ix_documents_created_at", table_name="documents")
    op.drop_table("documents")
