"""add conversations

Conversation state and the messages that make it up.

Autogenerate proposed dropping BOTH enum check constraints -- the ticket status
one and the review status one. The hazard is not specific to one table: any
constraint generated by ``Enum(create_constraint=True)`` rather than declared in
``__table_args__`` goes unmatched during comparison, so every autogenerated
draft offers to delete it. Both drops are removed here, and the guard test now
covers any such constraint rather than the ticket one alone.

Revision ID: 6cc81eefa78f
Revises: 73ce7d39be4c
Create Date: 2026-09-01 23:25:59.300580

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6cc81eefa78f"
down_revision: str | Sequence[str] | None = "73ce7d39be4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the conversation tables."""
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_conversations_customer_id_customers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_index('ix_conversations_customer_id', 'conversations', ['customer_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('customer', 'assistant', name='message_role_valid', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_estimate', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(content)) > 0', name=op.f('ck_conversation_messages_content_not_blank')),
    sa.CheckConstraint('position >= 0', name=op.f('ck_conversation_messages_position_non_negative')),
    sa.CheckConstraint('token_estimate >= 0', name=op.f('ck_conversation_messages_token_estimate_non_negative')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages')),
    sa.UniqueConstraint('conversation_id', 'position', name='uq_conversation_messages_conversation_id_position')
    )
    op.create_index('ix_conversation_messages_conversation_id_position', 'conversation_messages', ['conversation_id', 'position'], unique=False)


def downgrade() -> None:
    """Drop both tables, children first."""
    op.drop_index('ix_conversation_messages_conversation_id_position', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_conversations_customer_id', table_name='conversations')
    op.drop_table('conversations')
